name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   
      
    - name: Get ISO
      run: make download
      
    - name: Initialize
      run: make init
      
    - name: Setup env
      run: make setup

    - name: Build ISO
      run: make geniso

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
        name: Upload ISO # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ubuntu-custom*
        # The desired behavior if no files are found using the provided path.
        retention-days: 1
